name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup-msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: msys2-devel base-devel autotools cocom diffutils gcc gettext-devel libiconv-devel make mingw-w64-cross-crt mingw-w64-cross-gcc mingw-w64-cross-zlib perl zlib-devel xmlto docbook-xsl

      - name: Build
        shell: msys2 {0}
        run: |
          (cd winsup && ./autogen.sh)
          ./configure --disable-dependency-tracking --with-msys2-runtime-commit="$GITHUB_SHA"
          make -j8

      - name: Install
        shell: msys2 {0}
        run: |
          make DESTDIR="$(pwd)"/_dest install

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: install
          path: _dest/

  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - id: matrix
        uses: jeremyd2019/msys2-tests/gha-matrix-gen@composite-action

  test:
    needs: [build, generate-matrix]
    strategy:
      fail-fast: false
      matrix: 
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    name: ${{ matrix.msystem }}-${{ matrix.cc }}
    runs-on: ${{ matrix.runner }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      FC: ${{ matrix.fc }}
    steps:
      - uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: ${{ matrix.packages }}

      - uses: actions/download-artifact@v4
        with:
          name: install
          path: install

      - name: replace runtime files
        shell: bash
        run: |
          tar -C install -cf - . | tar -C "$(cygpath -u '${{ steps.msys2.outputs.msys2-location }}')" -xvf -

      - name: uname -a
        shell: msys2 {0}
        run: uname -a

      - name: Run tests
        uses: jeremyd2019/msys2-tests@composite-action
